In [1]:
import numpy as np

In [16]:
a = np.random.random((3,4))
print(a)

[[0.53721395 0.29951004 0.90651833 0.32391026]
 [0.54959312 0.28371674 0.22545092 0.44069318]
 [0.24001588 0.54378292 0.10115269 0.43192738]]


In [37]:
b = np.array([np.arange(10),np.arange(10)])
b.min(axis=1)

array([0, 0])

In [38]:
c= np.arange(10)

In [63]:
d = c.reshape((5,2))
d[:,0]

array([0, 2, 4, 6, 8])

In [64]:
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])